/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.ArrayList;

/**
 *
 * @author elijahhunt93
 */
public class FoodClient2 extends javax.swing.JFrame {
private static Socket clientSocket = null;
private static DataOutputStream os = null;
private static DataInputStream is = null;
private static BufferedReader inputline;

//used to store the text thats going in the text area
public static ArrayList<String> text = new  ArrayList<String>();

    /**
     * Creates new form TryClient2
     */
    public FoodClient2() {
        initComponents();
        orderreadybtn.setVisible(false);
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        orders = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        namebtn = new javax.swing.JButton();
        foodplace = new javax.swing.JComboBox<>();
        orderreadybtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        people = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        orders.setEditable(false);
        orders.setColumns(20);
        orders.setRows(5);
        jScrollPane1.setViewportView(orders);

        jLabel1.setText("Enter Name");

        namebtn.setText("Send name");
        namebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namebtnActionPerformed(evt);
            }
        });

        foodplace.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chick Fila", "Moes" }));
        foodplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodplaceActionPerformed(evt);
            }
        });

        orderreadybtn.setText("Send");
        orderreadybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderreadybtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Let customer know that their food is ready");

        jLabel3.setText("List of orders");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namebtn)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(foodplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(people, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(orderreadybtn)))
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(foodplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(namebtn)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(people, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orderreadybtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namebtnActionPerformed
        // TODO add your handling code here:
        String name = "";
        try{
           name = (String)foodplace.getSelectedItem();
           os.writeUTF(name);
           os.writeUTF("");
           setTitle(name);
           os.flush();
           namebtn.setVisible(false);
           System.out.println("name sent");
        }catch(IOException e){
            
        }
    }//GEN-LAST:event_namebtnActionPerformed

    private void orderreadybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderreadybtnActionPerformed
        // TODO add your handling code here:
        String ready = "";
        try{
        ready = people.getSelectedItem() + " your order is ready for pickup";
        os.writeUTF(ready);
         for(int i = 0; i < text.size(); i++){
           if(text.get(i).contains((String) people.getSelectedItem())){
               text.remove(i);
               break;
           }
       }
       people.removeItem(people.getSelectedItem());
        orders.setText("\n" +text.toString());
        }catch(IOException e){
        }
    }//GEN-LAST:event_orderreadybtnActionPerformed

    private void foodplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodplaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodplaceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoodClient2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoodClient2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoodClient2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoodClient2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FoodClient2().setVisible(true);
            }
        });

        try{
        System.out.println("Connected to server");
        clientSocket = new Socket("localhost", 2222);
            inputline = new BufferedReader(new InputStreamReader(System.in));
            os = new DataOutputStream(clientSocket.getOutputStream());
            is = new DataInputStream(clientSocket.getInputStream());
            
            String  msgin = "";
            while(!msgin.equals("exit")){
              msgin = is.readUTF();
         if(msgin.equals("please submit name")){
             System.out.println("\n" + msgin);
         }else if(!msgin.equals("please submit name")){
             break;   
         }
      }
          while(!msgin.equals("exit")){
              msgin = is.readUTF();
              if(msgin.startsWith("Hello")){
                  System.out.println("\n" + msgin);
                  os.writeUTF("hey");
                  os.flush();
              }else {
                  break;
              }
          }
          
          while(!msgin.equals("exit")){
              msgin = is.readUTF();
              if(msgin.contains(":") && !msgin.contains(" hey")){
                 String n = msgin.substring(0, msgin.indexOf(":"));
                 text.add("\n-------------" +"\n\n New Order" + "\n\n"+msgin);
                 orders.setText( "\n" +  text.toString());
                 people.addItem(n);
                 orderreadybtn.setVisible(true);
                 System.out.println("\n" + msgin);
             }else if(msgin.contains(" hey"))
                 System.out.println(msgin);
          }         
          
        }catch(UnknownHostException e){
            System.out.println(e);
        }
        catch(IOException e){
            System.out.println(e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JComboBox<String> foodplace;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton namebtn;
    private static javax.swing.JButton orderreadybtn;
    private static javax.swing.JTextArea orders;
    private static javax.swing.JComboBox<String> people;
    // End of variables declaration//GEN-END:variables
}
